version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      APP_MODE: prod
    volumes:
      - /home/bingym/services/data:/app/data
    ports:
      - "9993:80"
