version: '3'
services:
  webapp:
    image: registry.cn-hangzhou.aliyuncs.com/bingym/ipcat:latest
    restart: always
    expose:
      - "80"
    environment:
      APP_MODE: prod
    volumes:
      - /home/bingym/services/ipcat/data:/app/data
    ports:
      - "9993:80"
